baseurl = "http://docs.848.productions/Maven"
languageCode = "en-us"
title = "Maven Tutorial"
theme = "hyde"
copyright = "Will Sloan"

[Author]
	name = "Tech Team 1"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "A Tutorial by Ben Oberhaus, Maggie Gilbert, Reid Fu, Tyler Zeller, and Will Sloan"
